# (2주차) 3월14일

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의노트 

> youtube: https://youtube.com/playlist?list=PLQqh36zP38-z8oR8bQZHR0mpy_9OcsWOz

### import 

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.config.experimental.list_physical_devices('GPU')

[]

### tf.constant 

#### 예비학습: 중첩리스트 

`-` 리스트

In [ ]:
lst = [1,2,4,5,6]
lst 

[1, 2, 4, 5, 6]

In [ ]:
lst[1] # 두번쨰원소 

2

In [ ]:
lst[-1] # 마지막원소 

6

`-` (2,2) matrix 느낌의 list

In [ ]:
lst= [[1,2],[3,4]]
lst

[[1, 2], [3, 4]]

위를 아래와 같은 매트릭스로 생각할수 있다. 

```
1 2 
3 4 
```

In [ ]:
print(lst[0][0]) # (1,1) 
print(lst[0][1]) # (1,2) 
print(lst[1][0]) # (2,1) 
print(lst[1][1]) # (2,2) 

1
2
3
4


`-` (4,1) matrix 느낌의 list 

In [ ]:
lst=[[1],[2],[3],[4]] # (4,1) matrix = 길이가 4인 col-vector
lst

[[1], [2], [3], [4]]

`-` (1,4) matrix 느낌의 list 

In [ ]:
lst=[[1,2,3,4]] # (1,4) matrix = 길이가 4인 row-vector 
lst

[[1, 2, 3, 4]]

#### 선언

`-` 스칼라 

In [ ]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [ ]:
tf.constant(3.14)+tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=6.28>

`-` 벡터

In [ ]:
_vector=tf.constant([1,2,3])

In [ ]:
_vector[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

`-` 매트릭스

In [ ]:
_matrix= tf.constant([[1,0],[0,1]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

`-` array

In [ ]:
tf.constant([[[0,1,1],[1,2,-1]],[[0,1,2],[1,2,-1]]])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  1],
        [ 1,  2, -1]],

       [[ 0,  1,  2],
        [ 1,  2, -1]]], dtype=int32)>

#### 타입

In [ ]:
type(tf.constant(3.14))
# EagerTensor??

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [ ]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
_matrix[0][0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
_matrix[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
_matrix[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
_matrix[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한점
1. 모든 원소가 `같은` dtype을 가지고 있어야함. 
2. `원소 수정`이 `불가능`함. 
3. 묵시적 형변환이 불가능하다. 
  - 1+2.3 = 3.3
  - 이게 tf.constant에선 안 된다.
  - 아래 예시 코드를 살펴보자

In [ ]:
1+2.3

3.3

In [ ]:
# tf.constant(1)+tf.constant(2.3)
# error 발생 code

# 즉 묵시적 형변환이 되지 않음을 알 수 있다. 

`-` 원소수정이 불가능함 

In [ ]:
a=tf.constant([1,22,33])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1, 22, 33], dtype=int32)>

In [ ]:
# a[0]=11
# error 발생 code

# 원래 1이었던 원소는 11로 변경 불가능하다.
# tf.constant에서..

`-` 같은 float도 안되는 경우가 있음 

In [ ]:
tf.constant(1.0,dtype=tf.float64)
# 이건 float64

# 원래 tf.constant(1.0)도 float32이지만
# float32와 float64가 계산되지 않는다는 것을 설명하기 위해
# dtype=float64로 배정해주었음

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [ ]:
tf.constant(3.14)
# 이건 float32

# 그래서 float64와 계산이 안 됨

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [ ]:
tf.constant(1.0,dtype=tf.float32)+tf.constant(3.14)
# 이렇게 바꿔주면 계산이 된다. 

<tf.Tensor: shape=(), dtype=float32, numpy=4.1400003>

#### tf.constant $\to$ 넘파이 

In [ ]:
np.array(tf.constant(1)) # 방법1

array(1, dtype=int32)

In [ ]:
a=tf.constant([3.14,-3.14])
type(a)
# EagerTensor

tensorflow.python.framework.ops.EagerTensor

In [ ]:
a.numpy()

array([ 3.14, -3.14], dtype=float32)

In [ ]:
# 혹은
np.array(a)

array([ 3.14, -3.14], dtype=float32)

#### 연산

`-` 더하기 

In [ ]:
a=tf.constant([1,2])
b=tf.constant([3,4])
a+b
# numpy처럼 원소별 덧셈이 가능하다. 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [ ]:
tf.add(a,b)
# 덧셈 method

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

`-` 곱하기

In [ ]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [ ]:
tf.multiply(a,b)
# 곱셈 method

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

`-` 매트릭스의곱 

In [ ]:
a=tf.constant([[1,0],[0,1]]) # (2,2)
b=tf.constant([[5],[7]]) # (2,1) 
a@b #  2 by 1 

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

In [ ]:
tf.matmul(a,b)
# 행렬곱 method

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[5],
       [7]], dtype=int32)>

`-` 역행렬 

In [ ]:
a=tf.constant([[1,0],[0,2]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [ ]:
# tf.linalg.inv(a)

# error 발생 float으로 바꾸어줘야 한다.
# dtype=tf.float32
# dtype=tf.float64
# 둘다 가능하다.

In [ ]:
a=tf.constant([[1.0,0.0],[0.0,2.0]], dtype=tf.float64)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0. ],
       [0. , 0.5]])>

`-` `tf.linalg.` + `tab`을 누르면 좋아보이는 연산들 많음 

In [ ]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
print(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
tf.linalg.det(a)
# 행렬식

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [ ]:
tf.linalg.trace(a)
# 대각합

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

#### 형태변환

`-` 기본: tf.reshape() 를 이용

In [ ]:
a=tf.constant([1,2,3,4])
# row-vector
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.reshape(a,(4,1))
# col-vector로 변경

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [ ]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tf.reshape(a,(2,2,1))
# 3차원?

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

`-` 다차원

In [ ]:
a=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [ ]:
tf.reshape(a,(3,2,2))
# 3차원?

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [ ]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

`-` tf.resh

In [ ]:
a=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [ ]:
tf.reshape(a,(4,-1))
# 4행으로 만들 건데~ 그게 몇열이 될지는 모르겠어~

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.reshape(a,(2,2,-1))
# 일단 3차원으로 만들긴 할 건데~
# 일단 2행이고~
# 그럼 열은 어떻게 될진 모르겠으니 알아서 계산해~

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
b=tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tf.reshape(b,-1)
# row-vector

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

#### 선언고급 

`-` 다른 자료형 (리스트나 넘파이)로 만들고 바꾸는것도 좋다.

In [ ]:
np.diag([1,2,3,4])
# 대각행렬

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
tf.constant(np.diag([1,2,3,4]))
# np => tf.constant

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>

`-` tf.ones, tf.zeros

In [ ]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.reshape(tf.constant([0]*9),(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

`-` range(10) 

In [ ]:
a=range(0,12)
tf.constant(a)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [ ]:
tf.constant(range(1,20,3)) 

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19], dtype=int32)>

`-` tf.linspace

In [ ]:
tf.linspace(0,1,10)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

#### tf.concat 

`-` (2,1) concat (2,1) => (2,2)
- 두번째 축이 바뀌었다. => axis=1로 설정해주면 된다

In [ ]:
a=tf.constant([[1],[2]]) # 2 by 1
b=tf.constant([[3],[4]]) # 2 by 1
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

In [ ]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

`-` (2,1) concat (2,1) => (4,1)
- 첫번째 축이 바뀌었다. => axis=0로 설정해주면 된다
- 아래로 쌓는다고 생각해주면 된다

In [ ]:
a=tf.constant([[1],[2]])
b=tf.constant([[3],[4]])
a,b

(<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[1],
        [2]], dtype=int32)>, <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[3],
        [4]], dtype=int32)>)

In [ ]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

`-` (1,2) concat (1,2) => (2,2) 
- 첫번째 // axis=0

In [ ]:
a=tf.constant([[1,2]])
b=tf.constant([[3,4]])

In [ ]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

`-` (1,2) concat (1,2) => (1,4) 
- 첫번째 // axis=0

`-` (2,3,4,5) concat (2,3,4,5) => (4,3,4,5) 
- 첫번째 // axis=0

In [ ]:
a=tf.reshape(tf.constant(range(120)),(2,3,4,5))
b=-a

In [ ]:
tf.concat([a,b],axis=0)
# 아래로 쌓기

<tf.Tensor: shape=(4, 3, 4, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]]],


       [[[  60,   61,   62,   63,   64],
         [  65,   66,   67,   68,   69],
         [  70,   71,   72,   73,   74],
         [  75,   76,   77,   78,   79]],

        [[  80,   81,   82,   83,   84],
         [  85,   86,   87,   88,   89],
         [  90,   91,   92,   93,   94],
         [  95,   96,   97,   98,   99]],

        [[ 100,  101,  102,  103,  104],
         [ 105,  106,  107,  108,  109],
         [ 110,  111,  112,  113, 

`-` (2,3,4,5) concat (2,3,4,5) => (2,6,4,5) 
- 두번째 // axis=1

In [ ]:
a=tf.reshape(tf.constant(range(120)),(2,3,4,5))
b=-a

In [ ]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 6, 4, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -

`-` (2,3,4,5) concat (2,3,4,5) => (2,3,8,5) 
- 세번째 // axis=2

In [ ]:
a=tf.reshape(tf.constant(range(120)),(2,3,4,5))
b=-a

In [ ]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 8, 5), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39],
         [ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59],
         [ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -54],
 

`-` (2,3,4,5) concat (2,3,4,5) => (2,3,4,10) 
- 네번째 // axis=3 # 0,1,2,3 // -4 -3 -2 -1

In [ ]:
a=tf.reshape(tf.constant(range(120)),(2,3,4,5))
b=-a

In [ ]:

tf.concat([a,b],axis=-1)

<tf.Tensor: shape=(2, 3, 4, 10), dtype=int32, numpy=
array([[[[   0,    1,    2,    3,    4,    0,   -1,   -2,   -3,   -4],
         [   5,    6,    7,    8,    9,   -5,   -6,   -7,   -8,   -9],
         [  10,   11,   12,   13,   14,  -10,  -11,  -12,  -13,  -14],
         [  15,   16,   17,   18,   19,  -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24,  -20,  -21,  -22,  -23,  -24],
         [  25,   26,   27,   28,   29,  -25,  -26,  -27,  -28,  -29],
         [  30,   31,   32,   33,   34,  -30,  -31,  -32,  -33,  -34],
         [  35,   36,   37,   38,   39,  -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44,  -40,  -41,  -42,  -43,  -44],
         [  45,   46,   47,   48,   49,  -45,  -46,  -47,  -48,  -49],
         [  50,   51,   52,   53,   54,  -50,  -51,  -52,  -53,  -54],
         [  55,   56,   57,   58,   59,  -55,  -56,  -57,  -58,  -59]]],


       [[[  60,   61,   62,   63,   64,  -60,  -61,  -62,  -63,  -64],
         [  65, 

`-` (4,) concat (4,) => (8,)
- 첫번째축? // axis=0

In [ ]:
a=tf.constant([1,2,3,4]) # row-vector
b=-a 
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [ ]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4], dtype=int32)>

`-` (4,) concat (4,) => (4,2) 
- 두번째축? // axis=1 ==> 이런거없다..

In [ ]:
a=tf.constant([1,2,3,4])
b=-a 
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [ ]:
# tf.concat([a,b],axis=1)
# error code

#### tf.stack 

In [ ]:
a=tf.constant([1,2,3,4])
b=-a 
a,b

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2, -3, -4], dtype=int32)>)

In [ ]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4]], dtype=int32)>

In [ ]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2],
       [ 3, -3],
       [ 4, -4]], dtype=int32)>

### tnp

`-` tf는 넘파이에 비하여 텐서만들기가 너무힘듬 

In [ ]:
np.diag([1,2,3]).reshape(-1)

array([1, 0, 0, 0, 2, 0, 0, 0, 3])

- 넘파이는 이런식으로 `np.diag()`도 쓸수 있고 reshape을 메소드로 쓸 수도 있는데... 
  - tf는 변수 지정해주고 다음 단계로 넘겨서 reshape을 했어야 했음

#### tnp 사용방법 (불만해결방법)

In [ ]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

In [ ]:
type(tnp.array([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

`-` int와 float을 더할 수 있음
  - 즉, 묵시적 형변환이 가능하다

In [ ]:
tnp.array([1,2,3])+tnp.array([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [ ]:
tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

In [ ]:
tnp.array(1)+tnp.array([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [ ]:
tnp.diag([1,2,3])

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

In [ ]:
a=tnp.diag([1,2,3])
type(a)
# EagerTensor??

tensorflow.python.framework.ops.EagerTensor

In [ ]:
a=tf.constant([1,2,3])
a.reshape(3,1)
# 이렇게 넘파이처럼 메서드를 쓸 수 있게 되었다. 
# tnp.experimental_enable_numpy_behavior() 덕분

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

#### 선언고급

In [ ]:
np.random.randn(5)

array([ 0.49319663,  2.75517893, -1.43131833,  1.05555047,  0.3142022 ])

In [ ]:
tnp.random.randn(5) # 넘파이가 되면 나도 된다.

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 0.43632542, -0.60942648, -1.74066962,  0.6580403 , -0.21473674])>

#### 타입

In [ ]:
type(tnp.random.randn(5))

tensorflow.python.framework.ops.EagerTensor

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

`-` 묵시적형변환이 가능

In [ ]:
tf.constant([1,1])+tf.constant([2.2,3.3])

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3.20000005, 4.29999995])>

`-` 메소드를 쓸수 있음. 

In [ ]:
a= tnp.array([[1,2,3,4]])
a.T

<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[1],
       [2],
       [3],
       [4]])>

#### 그렇지만 완벽히 np.array는 아님 
- 원소 재배정이 안 됨

`-` 원소를 할당하는것은 불가능 

In [ ]:
a=tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
a[0]=11

TypeError: ignored