### imports

In [11]:
# from fastai.vision.all import *  ## 이미지분석 
from fastai.collab import * ## 추천시스템
from fastai.text.all import * ## 텍스트분석 
from fastai.vision.gan import * ## GAN (이미지생성)

In [12]:
import pandas as pd

### fastai를 이용한 분석 steps

`-` 비교 

| |이미지분석(CNN) | 추천시스템 | 텍스트분석 | GAN | 
|:-:|:-:|:-:|:-:|:-:|
|1단계|ImageDataLoaders|CollabDataLoaders| TextDataLoaders | DataBlock -> dls |  
|2단계|cnn_learner()|collab_learner()| language_model_learner() | GANLearner.wgan() | 
|3단계|lrnr.fine_tune(1)|lrnr.fit()| lrnr.fit() | lrnr.fit() |
|4단계|lrnr.predict(), lrnr.model(X)|lrnr.model(X)| lrnr.predict() | | 

## 추천시스템

In [13]:
df_view = pd.read_csv("https://raw.githubusercontent.com/guebin/DL2022/master/_notebooks/2022-09-08-rcmd_view.csv")

In [14]:
df_view.head(3)
# 유저 0~49까지는 커피 선호, 그 나머지 반절은 홍차 선호
# 교수님께서 임의로 배정한 dataset임

# 그런데 이 dataset은 컴퓨터가 선호하는 dataset이 아님
# 아래 df라는 dataset이 컴퓨터가 선호하는 dataset

# NaN이 많음
# sparse한 data임
# 압축하기 용이함
# SVD를 이용하면 가능할 것 같음

# 암튼 df_view는 컴퓨터가 그닥 선호하지 않는다.
# tidy data 형태인 df를 이용해보자

커피1       커피2  커피3       커피4       커피5       커피6  커피7       커피8  \
0  4.149209       NaN  NaN  4.078139  4.033415  4.071871  NaN       NaN   
1  4.031811       NaN  NaN  3.822704       NaN       NaN  NaN  4.071410   
2  4.082178  4.196436  NaN  3.956876       NaN       NaN  NaN  4.450931   

        커피9  커피10       홍차1       홍차2       홍차3       홍차4       홍차5       홍차6  \
0       NaN   NaN  1.142659  1.109452       NaN  0.603118  1.084308       NaN   
1  3.996206   NaN       NaN  0.839565  1.011315       NaN  1.120552  0.911340   
2  3.972090   NaN       NaN       NaN       NaN  0.983838       NaN  0.918576   

        홍차7       홍차8       홍차9      홍차10  
0  0.906524       NaN       NaN  0.903826  
1       NaN  0.860954  0.871482       NaN  
2  1.206796  0.913116       NaN  0.956194

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/guebin/DL2022/master/_notebooks/2022-09-08-rcmd_anal.csv")

In [16]:
df.head(3)
# 컴퓨터가 좋아하는 dataset 형태임
# 확실하진 않지만 이 형태의 dataset이 메모리 공간을 덜 차지할 것임
# tidy data여서 좋기도 함

user  item    rating item_name
0     1    15  1.084308       홍차5
1     1     1  4.149209       커피1
2     1    11  1.142659       홍차1

## 1단계

In [17]:
# 추천시스템 이용하기 위한 라이브러리 import
# from fastai.collab import *
dls = CollabDataLoaders.from_df(df)
# dls = dataloaders의 약어

In [21]:
dls.show_batch(max_n=4)

In [22]:
dls.one_batch()
# 두 tensor가 tuple로 이루어져 있음
# 따라서 두 개의 변수로 저장할 수 있음

# 첫 번째 tensor는 유저와 아이템
# 두 번째 tensor는 평점

(tensor([[ 6, 20],
         [88, 13],
         [61,  2],
         [56,  1],
         [11, 10],
         [71, 19],
         [40,  4],
         [74, 20],
         [90, 10],
         [75, 11],
         [13,  6],
         [12,  9],
         [11,  3],
         [53, 14],
         [48, 11],
         [42,  1],
         [88,  2],
         [41, 14],
         [ 9,  5],
         [86,  7],
         [57,  8],
         [93, 18],
         [ 1,  5],
         [26,  5],
         [50,  1],
         [78,  1],
         [68,  3],
         [76, 19],
         [61,  4],
         [79, 18],
         [36,  1],
         [27,  1],
         [33, 16],
         [42,  7],
         [99, 15],
         [ 3, 17],
         [62, 10],
         [31, 13],
         [48,  8],
         [ 2, 16],
         [ 1, 11],
         [27,  8],
         [39, 14],
         [ 8, 14],
         [63,  2],
         [68,  2],
         [ 4, 11],
         [67, 16],
         [ 1, 15],
         [49,  9],
         [30,  5],
         [ 5, 16],
         [34

In [23]:
X,y = dls.one_batch()

In [24]:
X[0],y[0]

(tensor([92,  4]), tensor([1.0577]))

## 2단계

In [25]:
lrnr = collab_learner(dls, y_range=(0,5))

In [26]:
id(dls)

140493103765968

In [27]:
id(lrnr.dls)

140493103765968

In [29]:
lrnr.dls.show_batch()
# dls.show_batch()와 결과가 동일하게 반환됨

# dls라는 오브젝트와 lrnr.dls는 동일 주소임
# dls와 동일한 오브젝트임
# id를 통해 동일 주소임을 확인할 수 있다. 

# 이름만 다름, 변수만 여러개로 binding한 것!

## 3단계

In [ ]:
lrnr.fit(10)

## 4단계 
- 하나의 배치 전체를 예측

In [92]:
X

tensor([[ 94,  11],
        [ 14,  17],
        [ 43,  10],
        [ 56,  17],
        [ 76,   9],
        [ 39,   4],
        [ 25,   1],
        [ 93,  17],
        [ 92,  20],
        [ 67,  19],
        [  3,  14],
        [ 22,  13],
        [ 80,  14],
        [ 42,  10],
        [ 95,  13],
        [ 98,  14],
        [ 54,  19],
        [ 11,   8],
        [ 42,   7],
        [ 52,  18],
        [ 48,   7],
        [ 84,  14],
        [ 95,  17],
        [  9,   7],
        [ 22,   5],
        [ 20,  15],
        [ 85,  12],
        [ 42,   1],
        [ 55,  20],
        [ 49,   8],
        [ 75,  17],
        [ 16,  12],
        [ 41,   2],
        [ 47,   1],
        [ 47,  10],
        [ 60,  19],
        [ 84,  10],
        [ 52,  16],
        [ 78,  13],
        [  1,  20],
        [ 48,  11],
        [ 86,   7],
        [ 81,  10],
        [ 23,  14],
        [ 65,  10],
        [ 80,  16],
        [ 70,  10],
        [ 47,  11],
        [ 67,   1],
        [ 71,  15],


In [95]:
yhat = lrnr.model(X)
# gpu로 올리는 방법
# lrnr.model(X.to("cuda:0"))

In [22]:
yhat

tensor([2.5063, 2.4914, 2.5044, 2.4992, 2.5277, 2.4952, 2.5165, 2.5132, 2.5034,
        2.4855, 2.5268, 2.5008, 2.5009, 2.5243, 2.5194, 2.4847, 2.4927, 2.5386,
        2.5334, 2.5181, 2.4993, 2.4906, 2.4745, 2.4857, 2.5006, 2.4667, 2.4994,
        2.5077, 2.5161, 2.5305, 2.5111, 2.4968, 2.4968, 2.4993, 2.4996, 2.4853,
        2.4957, 2.5239, 2.5081, 2.5200, 2.5285, 2.5329, 2.5014, 2.4924, 2.5017,
        2.5021, 2.4915, 2.5089, 2.5181, 2.4953, 2.5260, 2.5119, 2.4963, 2.5221,
        2.5120, 2.4867, 2.4855, 2.5089, 2.4943, 2.4853, 2.5216, 2.5244, 2.4913,
        2.5360], grad_fn=<AddBackward0>)

In [65]:
y
# yhat과 별로 유사 X
# lrnr.fit(10)
# 이 문장을 두어번 더 돌려보자

tensor([[3.9500],
        [3.8262],
        [0.9954],
        [4.1996],
        [1.2973],
        [4.0411],
        [4.0163],
        [0.6241],
        [0.7392],
        [4.2439],
        [1.0689],
        [1.1502],
        [3.8829],
        [1.1460],
        [4.1445],
        [3.8589],
        [3.7524],
        [1.1985],
        [4.1117],
        [3.8388],
        [3.8646],
        [0.9073],
        [4.0462],
        [1.0236],
        [0.9070],
        [0.7712],
        [1.0858],
        [3.8922],
        [0.9504],
        [1.0478],
        [1.1130],
        [3.8630],
        [3.9482],
        [4.0029],
        [0.8719],
        [0.9787],
        [3.8408],
        [3.8992],
        [0.8386],
        [1.0894],
        [4.4707],
        [1.0482],
        [4.1199],
        [0.9851],
        [4.0404],
        [0.9823],
        [4.1378],
        [4.0695],
        [3.9200],
        [3.9136],
        [0.7197],
        [0.8487],
        [1.2363],
        [3.9750],
        [0.8629],
        [1

In [ ]:
lrnr.fit(10)

In [ ]:
lrnr.fit(10)

In [68]:
yhat

tensor([4.0290, 4.0751, 0.9495, 4.0743, 1.1004, 3.9246, 4.0267, 1.1053, 0.9191,
        4.0861, 0.9452, 1.0944, 3.9468, 1.0536, 3.9640, 4.1108, 3.9609, 0.9494,
        4.0805, 3.9543, 3.9612, 1.0021, 3.9365, 1.1023, 1.0328, 0.9125, 1.0196,
        4.1621, 0.9685, 1.0514, 1.0840, 3.9669, 4.0595, 3.8977, 0.9095, 1.0641,
        3.9053, 3.9120, 0.8186, 0.9256, 4.0411, 1.0629, 3.9927, 1.0292, 3.9426,
        0.9368, 4.0141, 4.0716, 3.9496, 4.0230, 0.8709, 0.8746, 1.0849, 3.9980,
        1.1282, 1.0584, 4.1605, 4.0778, 1.1244, 1.1932, 3.9457, 4.0109, 0.9333,
        4.0116], grad_fn=<AddBackward0>)

In [69]:
y

tensor([[3.9500],
        [3.8262],
        [0.9954],
        [4.1996],
        [1.2973],
        [4.0411],
        [4.0163],
        [0.6241],
        [0.7392],
        [4.2439],
        [1.0689],
        [1.1502],
        [3.8829],
        [1.1460],
        [4.1445],
        [3.8589],
        [3.7524],
        [1.1985],
        [4.1117],
        [3.8388],
        [3.8646],
        [0.9073],
        [4.0462],
        [1.0236],
        [0.9070],
        [0.7712],
        [1.0858],
        [3.8922],
        [0.9504],
        [1.0478],
        [1.1130],
        [3.8630],
        [3.9482],
        [4.0029],
        [0.8719],
        [0.9787],
        [3.8408],
        [3.8992],
        [0.8386],
        [1.0894],
        [4.4707],
        [1.0482],
        [4.1199],
        [0.9851],
        [4.0404],
        [0.9823],
        [4.1378],
        [4.0695],
        [3.9200],
        [3.9136],
        [0.7197],
        [0.8487],
        [1.2363],
        [3.9750],
        [0.8629],
        [1

> ## ??

X[0]
- 이렇게 하면 error 발생
- 왜?
- 입력 형식의 문제임
- 코드 돌려보고 어떤 문제인지 알아보자

In [70]:
X[0:1]
# 해당 유저가 좋아할 음료는 무엇일지 predict 해보자

tensor([[54, 16]])

- 모델을 학습시켰으니 predict해보자

In [71]:
lrnr.model(X[0:1])

tensor([4.0165], grad_fn=<AddBackward0>)

In [72]:
# 하나의 유저가 하나의 아이템을 선택했다고 가정하고 예측(주어진 자료중에서 예측)

In [74]:
Xnew= torch.tensor([[1,2]])

In [75]:
lrnr.model(Xnew)

tensor([3.9671], grad_fn=<AddBackward0>)

In [77]:
Xnew= torch.tensor([[1,17]]) 
lrnr.model(Xnew)

tensor([1.1092], grad_fn=<AddBackward0>)

## 텍스트분석

In [110]:
df  = pd.DataFrame({'text':['h e l l o . h e l l o ! h e l l o ? h e l l o !! h e l l o ??']*20000})

In [111]:
df.head(3)

text
0  h e l l o . h e l l o ! h e l l o ? h e l l o !! h e l l o ??
1  h e l l o . h e l l o ! h e l l o ? h e l l o !! h e l l o ??
2  h e l l o . h e l l o ! h e l l o ? h e l l o !! h e l l o ??

In [112]:
dls = TextDataLoaders.from_df(df, text_col = 'text', is_lm=True)
# text 생성에 관심이 있다면 is_lm = True

In [113]:
dls.show_batch()
## text가 x역할 , text_가 y역할
## xxbos??
## 

In [114]:
# 2단계

In [115]:
lrnr = language_model_learner(dls, AWD_LSTM)
# AWD_LSTM => 모형 like resnet

In [116]:
#3단계

In [117]:
lrnr.fit(1)

KeyboardInterrupt: ignored

In [ ]:
#lrnr.fit(10)
#이렇게 설정하면 당연히 학습이 더 잘 될 것

In [ ]:
lrnr.predict("h e", n_words=30)

## GAN (Generative Adversarial Network)

`-` 저자: 이안굿펠로우 (이름이 특이함. 좋은친구..) 
- 천재임 
- 지도교수가 요수아 벤지오 

`-` 논문 NIPS, 저는 이 논문 읽고 소름돋았어요.. 
- https://arxiv.org/abs/1406.2661 (현재시점, 38751회 인용되었음 $\to$ 48978회 인용..)

`-` 최근 10년간 머신러닝 분야에서 가장 혁신적인 아이디어이다. (얀르쿤, 2014년 시점..) 

`-` 무슨내용? 생성모형 

### 생성모형이란? (쉬운 설명)

> 만들수 없다면 이해하지 못한 것이다, 리처드 파인만 (천재 물리학자) 

`-` 사진속에 들어있는 동물이 개인지 고양이인지 맞출수 있는 기계와 개와 고양이를 그릴수 있는 기계중 어떤것이 더 시각적보에 대한 이해가 깊다고 볼수 있는가? 

`-` 진정으로 인공지능이 이미지를 이해했다면, 이미지를 만들수도 있어야 한다. $\to$ 이미지를 생성하는 모형을 만들어보자 $\to$ 성공 

![](https://upload.wikimedia.org/wikipedia/commons/1/1f/Woman_1.jpg)

#### GAN의 응용분야

`-` 내가 찍은 사진이 피카소의 화풍으로 표현된다면?

`-` 퀸의 라이브에이드가 4k로 나온다면?

`-` 1920년대 서울의 모습이 칼라로 복원된다면? 

`-` 딥페이크: 유명인의 가짜 포르노, 가짜뉴스, 협박(거짓기소) 


`-` 게임영상 (파이널판타지)

`-` 거북이의 커버.. 

`-` 너무 많아요.....

### 생성모형이란? 통계학과 버전의 설명 

> 제한된 정보만으로 어떤 문제를 풀 떄, 그 과정에서 원래의 문제보다 일반적인 문제를 풀지 말고, 가능한 원래의 문제를 직접 풀어야한다. 배프닉 (SVM 창시자) 

`-` 이미지 $\boldsymbol{x}$가 주어졌을 경우 라벨을 $y$라고 하자. 

`-` 이미지를 보고 라벨을 맞추는 일은 $p(y| \boldsymbol{x})$에 관심이 있는 것과 동일하다.

`-` 이미지를 생성하는 일은 $p(\boldsymbol{x},y)$에 관심이 있는것이다. 

`-` 데이터의 생성확률 $p(\boldsymbol{x},y)$을 알면 클래스의 사후확률 $p(y|\boldsymbol{x})$를 알 수 있음. (아래의 수식 참고) 하지만 역은 불가능 

$$p(y|x) = \frac{p(x,y)}{p(x)} = \frac{p(x,y)}{\sum_{y}p(x,y)} $$

- 즉 이미지를 생성하는일은 분류문제보다 더 어려운 일이라 해석가능 

`-` 따라서 배프닉의 원리에 의하면 식별적 분류가 생성적 분류보다 바람직한 접근법이라 할 수 있음. 

`-` 하지만 다양한 현실문제에서 생성모형이 유용할때가 많다. 

### GAN의 원리

`-` GAN은 생성모형중 하나임 

`-` GAN의 원리는 경찰과 위조지폐범이 서로 선의의(?) 경쟁을 통하여 서로 발전하는 모형으로 설명할 수 있다. 

> The generative model can be thought of as analogous to a team of counterfeiters,
trying to produce fake currency and use it without detection, while the discriminative model is
analogous to the police, trying to detect the counterfeit currency. Competition in this game drives
both teams to improve their methods until the counterfeits are indistiguishable from the genuine
articles.

`-` 서로 적대적인(adversarial) 네트워크(network)를 동시에 학습시켜 가짜이미지를 만든다(generate) 

`-` 무식한 상황극.. 

> 위조범: 가짜돈을 만들어서 부자가 되어야지! (가짜돈을 그림) 

> 경찰: (위조범이 만든 돈을 보고) 이건 가짜다! 

> 위조범: 걸렸군.. 더 정교하게 만들어야지.. 

> 경찰: 이건 진짠가?... --> 상사에게 혼남. 그것도 구분못하냐고 

> 위조범: 더 정교하게 만들자.. 

> 경찰: 더 판별능력을 업그레이드 하자! 

> 반복.. 

`-` 굉장히 우수한 경찰조차도 진짜와 가짜를 구분하지 못할때(=진짜 이미지를 0.5의 확률로만 진짜라고 말할때 = 가짜 이미지를 0.5의 확률로만 가짜라고 말할때) 학습을 멈춘다. 

In [ ]:
!git add .

[master 7f6bb52] .
 1 file changed, 236 insertions(+), 12 deletions(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.71 KiB | 3.71 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/guebin/DL2022.git
   604fa18..7f6bb52  master -> master
